name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: test
  PORT: 3000
  MONGODB_CLUSTER_ADDRESS: cluster1.dlcb06m.mongodb.net
  MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
  MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    services:
      mongodb:
        image: mongo
        env:
          MONGODB_CLUSTER_ADDRESS: mongodb
          MONGODB_USERNAME: root
          MONGODB_PASSWORD: example
          MONGODB_DB_NAME: test
          PORT: 3000
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{runner.os}}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:3000
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "${{secrets.MONGODB_USERNAME}}"
